### ISSUE TITLE
Proposal: drop 'scope' property

### ISSUE THREAD

**Issue by dmitrizagidulin** [jasnell/w3c-socialwg-activitystreams#299] opened 2016-03-17 15:47 UTC
Please Indicate One: 
 * [ ] Editorial
 * [ ] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [x] Non-Blocking Issue

Please Describe the Issue:
The `scope` property (see [vocab#dfn-scope](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-scope)) seems to be trying to tackle access control functionality (which is handled in things like ActivityPub with the `to` field). 
The consensus in the face-to-face meeting is that it's ok to drop the `scope` property, however @jasnell voiced an objection. The resolution was to open an issue and hear the reasons / use case for scope.

**Comment by jasnell** [comment] 2016-03-17 15:51
Strong -1. See https://github.com/jasnell/w3c-socialwg-activitystreams/issues/300

I believe the rushed "consensus" at the F2F is based more on a a lack of understanding than a reasoned decision. The description in the vocabulary spec can be improved to better identify the differences.

**Comment by jasnell** [comment] 2016-04-04 17:55
Duplicate of #300

**Closed by jasnell** 2016-04-04 17:55 UTC
Labels: proposal
