### ISSUE TITLE
Best practices for #hashtags

### ISSUE THREAD

**Issue by evanp** [jasnell/w3c-socialwg-activitystreams#63] opened 2015-01-13 19:14 UTC
Many social systems use a in-band mechanism to let users define a category or topic for an object. For example, "#topic" will mark an image or text as being related to the topic "topic".

It would be worthwhile to note that Activity Streams 2.0 processors should not have to parse the "content" or other properties of activity objects to determine this category information.

Instead, the stream creator SHOULD add a "tag" property to the object and MAY change the "#topic" content to a link to a page about that topic (for example, one showing a stream of all objects related to that topic).

**Comment by akuckartz** [comment] 2015-01-20 06:09
Is this issue about annotations ?

**Comment by jasnell** [comment] 2015-01-20 15:20
The issue is about using inline hashtags in text fields such as comment, summary, etc and whether activity streams implementations ought to be required to rely on those. The decision of the WG was that no, publishers should make use of appropriate structured property fields to communicate tagging information. AS2 has the "tag" property. 

So rather than just saying...
```javascript
{ "@type": "Note", "content": "A test #note" }
```
We'd have something like:
```javascript
{ "@type": "Note", "content": "A test #note",
  "tag": { "@type": "Link", "href": "http://example.org/tags/note" } }
```
This makes tagging explicit without requiring processing of the text content.

**Comment by akuckartz** [comment] 2015-01-20 15:32
The "#note" in "A test #note" has no AS2 semantics different from "note" in "A test note", correct?

Or does "#" have an additional semantic in AS2 ?

**Comment by jasnell** [comment] 2015-01-20 15:39
Right, there are no additional semantics in AS2 for the #.

**Comment by jasnell** [comment] 2015-02-10 05:30
Addressed in the current published working draft

**Closed by jasnell** 2015-02-10 05:30 UTC
